spring:
  datasource:
    url: jdbc:mysql://db/myDatabase?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: false
      type: all
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: none
        temp:
          use_jdbc_metadata_defaults: false
